name: Deploy POOS Large Project

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '22.18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Deploy frontend to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "frontend/dist/*"
          target: "/var/www/${{ secrets.SERVER_HOST }}/html"
          strip_components: 2
          rm: true

      - name: Deploy backend files
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "server.js,package.json,package-lock.json"
          target: "/var/mainServer"
          overwrite: true

      - name: Create .env file on server
        uses: appleboy/ssh-action@v1.0.0
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/mainServer
            cat > .env << EOF
            MONGO_URI=${{ secrets.MONGO_URI }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            EOF  

      - name: Install dependencies and restart server
        uses: appleboy/ssh-action@v1.0.0
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/mainServer
            npm ci --production
            npm list -g pm2 || npm install -g pm2
            pm2 reload main-express-server --update-env || pm2 start server.js --name "main-express-server"
            pm2 save
            nginx -s reload